---
require:
  - rubocop-performance
  - rubocop-rubycw
  - rubocop-rake
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Exclude:
    - lib/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Enabled: false

Naming/AccessorMethodName:
   Enabled: false

Bundler/GemComment:
   Enabled: false
   Include:
     - Gemfile

Rubycw/Rubycw:
  Exclude:
    - ./*.md

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - vendor/**/*
