---
require:
  - rubocop-performance
  - rubocop-rubycw
  - rubocop-rake

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Metrics/AbcSize:
  Max: 20

Naming/AccessorMethodName:
   Enabled: false

Bundler/GemComment:
   Enabled: false
   Include:
     - Gemfile

Rubycw/Rubycw:
  Exclude:
    - ./*.md

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
