#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/awscli'

trap('SIGINT') do
  warn "\nExecution aborted.\n"
  exit 1
end

begin
  Awscli::Cli.start
rescue StandardError => e
  warn e
  exit 1
end
